import { MedicalReport } from "./types";
import defaultAvatar from "./assets/images/patient_avatar_1779277307280.png";

export const DEFAULT_AVATAR = defaultAvatar;

export const TEMPLATE_REPORT: MedicalReport = {
  id: "template-1",
  title: "Obydullah Haque (U.A.E - FIT)",
  createdAt: "2026-05-20T11:40:00Z",
  patient: {
    regNo: "AJ-26-3379",
    examDate: "07.05.2026",
    fullName: "OBYDULLAH HAQUE",
    fatherName: "AFJAL HOSAN",
    motherName: "MOMOTAJ MOHAL",
    passportNo: "A19154708",
    dob: "26.12.1981",
    sex: "MALE",
    agency: "JHRL/AF-1",
    photoUrl: DEFAULT_AVATAR,
    destinationCountry: "U.A.E",
  },
  physical: {
    height: "166 cm",
    weight: "65 kg",
    pulse: "82 bpm",
    bloodPressure: "120/80 mm of Hg",
    heart: "NAD",
    liver: "NORMAL",
    spleen: "NORMAL",
    eyeLeft: "6/6",
    eyeRight: "6/6",
    ent: "NAD",
    skin: "NORMAL",
    physicalCondition: "NORMAL",
    ecg: "Not Seen",
    chestP_A_View: "NORMAL",
  },
  labs: {
    serology: {
      hbsag: "NEGATIVE",
      vdrl: "NON-REACTIVE",
      tpha: "NEGATIVE",
      bloodGroup: '"O" (+ve)',
    },
    biochemical: {
      sBilirubin: "0.9 mg/dl",
      sugarRandom: "5.7 mmol/L",
    },
    hematology: {
      hemoglobin: "13.3 mg/dl",
    },
    urine: {
      pregnancyTest: "NOT APPLICABLE",
    },
  },
  fitStatus: "FIT",
  remarks: "",
  signatures: {
    checkedByName: "Md. Shohel Rana",
    checkedByTitle1: "DMT in Laboratory Medicine",
    checkedByTitle2: "Al-Jabbar Medical Center",
    doctorName: "DR. ALI AHSAN",
    doctorTitle1: "MBBS, DMU (SUB), MPH (C.M) BSMMU",
    doctorTitle2: "Medical Officer",
    doctorTitle3: "Al-Jabbar Medical Center",
    showCheckedSignature: true,
    showDoctorSignature: true,
    showCenterStamp: true,
  },
};

export const MALE_FIT_PRESET: Omit<MedicalReport, "id" | "createdAt" | "title"> = {
  patient: {
    regNo: "AJ-26-0000",
    examDate: new Date().toLocaleDateString("en-GB").replace(/\//g, "."),
    fullName: "NEW PATIENT",
    fatherName: "FATHER NAME",
    motherName: "MOTHER NAME",
    passportNo: "A00000000",
    dob: "01.01.1990",
    sex: "MALE",
    agency: "JHRL/AF-1",
    photoUrl: "",
    destinationCountry: "U.A.E",
  },
  physical: {
    height: "170 cm",
    weight: "70 kg",
    pulse: "72 bpm",
    bloodPressure: "120/80 mm of Hg",
    heart: "NAD",
    liver: "NORMAL",
    spleen: "NORMAL",
    eyeLeft: "6/6",
    eyeRight: "6/6",
    ent: "NAD",
    skin: "NORMAL",
    physicalCondition: "NORMAL",
    ecg: "NORMAL",
    chestP_A_View: "NORMAL",
  },
  labs: {
    serology: {
      hbsag: "NEGATIVE",
      vdrl: "NON-REACTIVE",
      tpha: "NEGATIVE",
      bloodGroup: '"A" (+ve)',
    },
    biochemical: {
      sBilirubin: "0.8 mg/dl",
      sugarRandom: "5.5 mmol/L",
    },
    hematology: {
      hemoglobin: "14.5 mg/dl",
    },
    urine: {
      pregnancyTest: "NOT APPLICABLE",
    },
  },
  fitStatus: "FIT",
  remarks: "",
  signatures: {
    checkedByName: "Md. Shohel Rana",
    checkedByTitle1: "DMT in Laboratory Medicine",
    checkedByTitle2: "Al-Jabbar Medical Center",
    doctorName: "DR. ALI AHSAN",
    doctorTitle1: "MBBS, DMU (SUB), MPH (C.M) BSMMU",
    doctorTitle2: "Medical Officer",
    doctorTitle3: "Al-Jabbar Medical Center",
    showCheckedSignature: true,
    showDoctorSignature: true,
    showCenterStamp: true,
  },
};

export const FEMALE_FIT_PRESET: Omit<MedicalReport, "id" | "createdAt" | "title"> = {
  patient: {
    regNo: "AJ-26-0000",
    examDate: new Date().toLocaleDateString("en-GB").replace(/\//g, "."),
    fullName: "NEW FEMALE PATIENT",
    fatherName: "FATHER NAME",
    motherName: "MOTHER NAME",
    passportNo: "A00000000",
    dob: "01.01.1995",
    sex: "FEMALE",
    agency: "JHRL/AF-1",
    photoUrl: "",
    destinationCountry: "U.A.E",
  },
  physical: {
    height: "160 cm",
    weight: "58 kg",
    pulse: "75 bpm",
    bloodPressure: "115/75 mm of Hg",
    heart: "NAD",
    liver: "NORMAL",
    spleen: "NORMAL",
    eyeLeft: "6/6",
    eyeRight: "6/6",
    ent: "NAD",
    skin: "NORMAL",
    physicalCondition: "NORMAL",
    ecg: "NORMAL",
    chestP_A_View: "NORMAL",
  },
  labs: {
    serology: {
      hbsag: "NEGATIVE",
      vdrl: "NON-REACTIVE",
      tpha: "NEGATIVE",
      bloodGroup: '"B" (+ve)',
    },
    biochemical: {
      sBilirubin: "0.7 mg/dl",
      sugarRandom: "5.2 mmol/L",
    },
    hematology: {
      hemoglobin: "12.5 mg/dl",
    },
    urine: {
      pregnancyTest: "NEGATIVE",
    },
  },
  fitStatus: "FIT",
  remarks: "",
  signatures: {
    checkedByName: "Md. Shohel Rana",
    checkedByTitle1: "DMT in Laboratory Medicine",
    checkedByTitle2: "Al-Jabbar Medical Center",
    doctorName: "DR. ALI AHSAN",
    doctorTitle1: "MBBS, DMU (SUB), MPH (C.M) BSMMU",
    doctorTitle2: "Medical Officer",
    doctorTitle3: "Al-Jabbar Medical Center",
    showCheckedSignature: true,
    showDoctorSignature: true,
    showCenterStamp: true,
  },
};
